/* ═══════════════════════════════════════════════════════════════════════════
   data2.js — extends window.KT with:
   · SVG map coordinates for all 23 clinics
   · ~46 additional doctors (2 per clinic, stacked on the original 6)
   · 20 service detail objects
   ═══════════════════════════════════════════════════════════════════════════ */
(function () {
  const KT = window.KT;

  /* ── Map coordinates (SVG 800×560, projected from real lat/lng) ───────── */
  const coords = {
    "agoura-hills":   [52,  224], "canyon-country": [230, 44],  "mission-hills":  [322, 142],
    "northridge":     [252, 164], "san-fernando":   [330, 127], "tarzana":        [235, 209],
    "valencia":       [226, 28],  "van-nuys":       [318, 194], "west-hills":     [148, 187],
    "arcadia":        [678, 231], "la-canada":      [539, 187], "pasadena":       [600, 224],
    "glendale":       [496, 231], "beverly-hills":  [365, 284], "culver-city":    [365, 321],
    "hollywood":      [435, 261], "santa-monica":   [287, 321], "downey":         [600, 381],
    "la-mirada":      [700, 411], "pico-rivera":    [635, 351], "san-pedro":      [461, 530],
    "torrance":       [417, 455], "whittier":       [687, 351],
  };
  KT.locations.forEach((l) => { l.x = coords[l.slug]?.[0] ?? 400; l.y = coords[l.slug]?.[1] ?? 280; });

  /* ── Expanded doctor roster (~2 per clinic) ───────────────────────────── */
  const extra = [
    // SFV
    { slug:"carlos-mendez",   name:"Dr. Carlos Méndez, MD",    specialty:"Pediatrics",           clinic:"Agoura Hills",  clinicSlug:"agoura-hills",   lang:"English, Spanish", accepting:true,  focus:["Well-child","Sick visits","Preventive care"],         edu:"MD, UCLA" },
    { slug:"lisa-park",       name:"Dr. Lisa Park, MD",         specialty:"Adolescent Medicine",  clinic:"Agoura Hills",  clinicSlug:"agoura-hills",   lang:"English, Korean",  accepting:true,  focus:["Teen health","Sports physicals","Mental wellness"],    edu:"MD, Keck USC" },
    { slug:"ricardo-vega",    name:"Dr. Ricardo Vega, DO",      specialty:"Pediatrics",           clinic:"Canyon Country",clinicSlug:"canyon-country",  lang:"English, Spanish", accepting:true,  focus:["Well-child","Urgent care","Vaccinations"],             edu:"DO, COMP Western" },
    { slug:"sarah-chen",      name:"Dr. Sarah Chen, MD",        specialty:"ADHD & Behavioral",    clinic:"Canyon Country",clinicSlug:"canyon-country",  lang:"English, Mandarin",accepting:true,  focus:["ADHD","Behavioral","Developmental"],                   edu:"MD, UC Davis" },
    { slug:"jose-ramirez",    name:"Dr. José Ramírez, MD",      specialty:"Pediatrics",           clinic:"Mission Hills", clinicSlug:"mission-hills",   lang:"English, Spanish", accepting:true,  focus:["Primary care","Newborn","Vaccinations"],               edu:"MD, Charles Drew Univ" },
    { slug:"emily-walsh",     name:"Dr. Emily Walsh, DO",       specialty:"Nutrition",            clinic:"Mission Hills", clinicSlug:"mission-hills",   lang:"English",          accepting:false, focus:["Nutrition","Childhood obesity","Growth"],               edu:"DO, Touro University" },
    { slug:"kevin-kim",       name:"Dr. Kevin Kim, MD",         specialty:"Pediatrics",           clinic:"Northridge",    clinicSlug:"northridge",      lang:"English, Korean",  accepting:true,  focus:["Well-child","Urgent care","Sick visits"],              edu:"MD, UCLA" },
    { slug:"fatima-ali",      name:"Dr. Fatima Ali, MD",        specialty:"Asthma & Allergy",     clinic:"Northridge",    clinicSlug:"northridge",      lang:"English, Urdu",    accepting:true,  focus:["Asthma","Allergy testing","Immunotherapy"],            edu:"MD, USC Keck" },
    { slug:"robert-guerrero", name:"Dr. Robert Guerrero, MD",   specialty:"Pediatrics",           clinic:"San Fernando",  clinicSlug:"san-fernando",    lang:"English, Spanish", accepting:true,  focus:["Community pediatrics","Preventive","School physicals"], edu:"MD, Loma Linda Univ" },
    { slug:"diana-flores",    name:"Dr. Diana Flores, DO",      specialty:"Adolescent Medicine",  clinic:"San Fernando",  clinicSlug:"san-fernando",    lang:"English, Spanish", accepting:true,  focus:["Teen wellness","Reproductive health","Mental health"], edu:"DO, Western University" },
    { slug:"john-nakamura",   name:"Dr. John Nakamura, MD",     specialty:"Pediatrics",           clinic:"Tarzana",       clinicSlug:"tarzana",         lang:"English, Japanese",accepting:true,  focus:["General pediatrics","Newborn","Immunizations"],        edu:"MD, UCLA" },
    { slug:"aisha-johnson",   name:"Dr. Aisha Johnson, MD",     specialty:"Infectious Disease",   clinic:"Tarzana",       clinicSlug:"tarzana",         lang:"English",          accepting:true,  focus:["Infectious disease","Fevers","Travel health"],         edu:"MD, Howard University" },
    { slug:"miguel-santos",   name:"Dr. Miguel Santos, MD",     specialty:"Pediatrics",           clinic:"Valencia",      clinicSlug:"valencia",        lang:"English, Spanish", accepting:true,  focus:["Well-child","Sports physicals","Urgent care"],         edu:"MD, Keck USC" },
    { slug:"jennifer-berg",   name:"Dr. Jennifer Berg, MD",     specialty:"Newborn Care",         clinic:"Valencia",      clinicSlug:"valencia",        lang:"English",          accepting:true,  focus:["Newborn care","Lactation support","NICU follow-up"],   edu:"MD, Stanford" },
    { slug:"omar-hassan",     name:"Dr. Omar Hassan, MD",       specialty:"Pediatrics",           clinic:"Van Nuys",      clinicSlug:"van-nuys",        lang:"English, Arabic, Somali",accepting:true,focus:["Primary care","Community health","Preventive"],    edu:"MD, UCLA" },
    { slug:"yuki-tanaka",     name:"Dr. Yuki Tanaka, MD",       specialty:"ADHD & Behavioral",    clinic:"Van Nuys",      clinicSlug:"van-nuys",        lang:"English, Japanese",accepting:false, focus:["ADHD","Autism spectrum","School readiness"],           edu:"MD, USC Keck" },
    { slug:"patricia-lozano", name:"Dr. Patricia Lozano, MD",   specialty:"Pediatrics",           clinic:"West Hills",    clinicSlug:"west-hills",      lang:"English, Spanish", accepting:true,  focus:["Well-child","Preventive care","Vaccinations"],         edu:"MD, UCSF" },
    { slug:"samuel-brown",    name:"Dr. Samuel Brown, DO",      specialty:"Sports Medicine",      clinic:"West Hills",    clinicSlug:"west-hills",      lang:"English",          accepting:true,  focus:["Sports injuries","Concussions","Orthopedic"],          edu:"DO, Pacific Western" },
    // SGV
    { slug:"mei-zhang",       name:"Dr. Mei Zhang, MD",         specialty:"Pediatrics",           clinic:"Arcadia",       clinicSlug:"arcadia",         lang:"English, Mandarin, Cantonese", accepting:true,focus:["Well-child","Developmental screening","Nutrition"],edu:"MD, UC San Francisco" },
    { slug:"alex-kim",        name:"Dr. Alex Kim, MD",          specialty:"Asthma & Allergy",     clinic:"Arcadia",       clinicSlug:"arcadia",         lang:"English, Korean",  accepting:true,  focus:["Asthma","Food allergies","Eczema"],                    edu:"MD, Stanford" },
    { slug:"anna-petrosyan",  name:"Dr. Anna Petrosyan, MD",    specialty:"Pediatrics",           clinic:"La Cañada",     clinicSlug:"la-canada",       lang:"English, Armenian",accepting:true,  focus:["Primary care","Well-child","Vaccinations"],            edu:"MD, USC Keck" },
    { slug:"david-wu",        name:"Dr. David Wu, MD",          specialty:"Adolescent Medicine",  clinic:"La Cañada",     clinicSlug:"la-canada",       lang:"English, Mandarin",accepting:true,  focus:["Teen health","Sports physicals","Eating disorders"],   edu:"MD, UCSF" },
    { slug:"michael-garcia",  name:"Dr. Michael García, MD",    specialty:"Pediatrics",           clinic:"Pasadena",      clinicSlug:"pasadena",        lang:"English, Spanish", accepting:true,  focus:["General pediatrics","Urgent care","Sick visits"],      edu:"MD, UCLA" },
    { slug:"nina-patel",      name:"Dr. Nina Patel, MD",        specialty:"Childhood Obesity",    clinic:"Pasadena",      clinicSlug:"pasadena",        lang:"English, Gujarati",accepting:true,  focus:["Childhood obesity","Nutrition","Metabolic health"],    edu:"MD, Yale" },
    { slug:"armen-khachaturian",name:"Dr. Armen Khachaturian, DO",specialty:"Pediatrics",         clinic:"Glendale",      clinicSlug:"glendale",        lang:"English, Armenian, Russian",accepting:true,focus:["Primary care","Newborn","Vaccinations"],          edu:"DO, Touro University" },
    { slug:"linda-tran",      name:"Dr. Linda Trần, MD",        specialty:"Infectious Disease",   clinic:"Glendale",      clinicSlug:"glendale",        lang:"English, Vietnamese",accepting:true, focus:["Infectious disease","COVID care","Fevers"],            edu:"MD, UC Irvine" },
    // Westside
    { slug:"rachel-stern",    name:"Dr. Rachel Stern, MD",      specialty:"Pediatrics",           clinic:"Beverly Hills", clinicSlug:"beverly-hills",   lang:"English, Hebrew",  accepting:true,  focus:["Concierge care","Well-child","Developmental"],         edu:"MD, Harvard" },
    { slug:"james-okonkwo",   name:"Dr. James Okonkwo, MD",     specialty:"Newborn Care",         clinic:"Beverly Hills", clinicSlug:"beverly-hills",   lang:"English",          accepting:false, focus:["Newborn","NICU follow-up","Lactation"],                edu:"MD, Columbia" },
    { slug:"Sandra-morales",  name:"Dr. Sandra Morales, MD",    specialty:"Pediatrics",           clinic:"Culver City",   clinicSlug:"culver-city",     lang:"English, Spanish", accepting:true,  focus:["Primary care","Well-child","Vaccinations"],            edu:"MD, UCLA" },
    { slug:"thomas-nguyen",   name:"Dr. Thomas Nguyễn, MD",     specialty:"ADHD & Behavioral",    clinic:"Culver City",   clinicSlug:"culver-city",     lang:"English, Vietnamese",accepting:true, focus:["ADHD","Behavioral","Anxiety"],                         edu:"MD, Keck USC" },
    { slug:"jessica-kim",     name:"Dr. Jessica Kim, MD",       specialty:"Pediatrics",           clinic:"Hollywood",     clinicSlug:"hollywood",       lang:"English, Korean",  accepting:true,  focus:["Well-child","Urgent care","Sick visits"],              edu:"MD, UCLA" },
    { slug:"paul-rodriguez",  name:"Dr. Paul Rodríguez, MD",    specialty:"Sports Medicine",      clinic:"Hollywood",     clinicSlug:"hollywood",       lang:"English, Spanish", accepting:true,  focus:["Sports injuries","Concussions","Musculoskeletal"],     edu:"MD, UC San Diego" },
    { slug:"helen-cho",       name:"Dr. Helen Cho, MD",         specialty:"Pediatrics",           clinic:"Santa Monica",  clinicSlug:"santa-monica",    lang:"English, Korean",  accepting:true,  focus:["General pediatrics","Newborn","Well-child"],           edu:"MD, UCLA" },
    { slug:"brendan-foster",  name:"Dr. Brendan Foster, DO",    specialty:"Nutrition",            clinic:"Santa Monica",  clinicSlug:"santa-monica",    lang:"English",          accepting:true,  focus:["Nutrition","Sports nutrition","Eating disorders"],     edu:"DO, Western University" },
    // South
    { slug:"rosa-cisneros",   name:"Dr. Rosa Cisneros, MD",     specialty:"Pediatrics",           clinic:"Downey",        clinicSlug:"downey",          lang:"English, Spanish", accepting:true,  focus:["Primary care","Urgent care","Vaccinations"],           edu:"MD, Charles Drew Univ" },
    { slug:"michael-le",      name:"Dr. Michael Lê, MD",        specialty:"Newborn Care",         clinic:"Downey",        clinicSlug:"downey",          lang:"English, Vietnamese",accepting:true, focus:["Newborn","Lactation support","NICU follow-up"],        edu:"MD, Keck USC" },
    { slug:"carmen-ruiz",     name:"Dr. Carmen Ruiz, MD",       specialty:"Pediatrics",           clinic:"La Mirada",     clinicSlug:"la-mirada",       lang:"English, Spanish", accepting:true,  focus:["Well-child","Sick visits","School physicals"],         edu:"MD, Loma Linda Univ" },
    { slug:"brian-park",      name:"Dr. Brian Park, MD",        specialty:"Adolescent Medicine",  clinic:"La Mirada",     clinicSlug:"la-mirada",       lang:"English, Korean",  accepting:false, focus:["Teen health","Mental health","Sports physicals"],      edu:"MD, UCLA" },
    { slug:"elena-medina",    name:"Dr. Elena Medina, DO",      specialty:"Pediatrics",           clinic:"Pico Rivera",   clinicSlug:"pico-rivera",     lang:"English, Spanish", accepting:true,  focus:["Community health","Well-child","Preventive care"],     edu:"DO, Touro University" },
    { slug:"victor-huang",    name:"Dr. Victor Huang, MD",      specialty:"Infectious Disease",   clinic:"Pico Rivera",   clinicSlug:"pico-rivera",     lang:"English, Mandarin",accepting:true,  focus:["Infectious disease","Fevers","Tropical medicine"],     edu:"MD, Stanford" },
    { slug:"mariela-santos",  name:"Dr. Mariela Santos, MD",    specialty:"Pediatrics",           clinic:"San Pedro",     clinicSlug:"san-pedro",       lang:"English, Spanish, Tagalog",accepting:true,focus:["Primary care","Well-child","Community health"],    edu:"MD, UCLA" },
    { slug:"william-jones",   name:"Dr. William Jones, MD",     specialty:"Asthma & Allergy",     clinic:"San Pedro",     clinicSlug:"san-pedro",       lang:"English",          accepting:true,  focus:["Asthma","Allergies","Eczema"],                         edu:"MD, USC Keck" },
    { slug:"angela-kim",      name:"Dr. Angela Kim, MD",        specialty:"Pediatrics",           clinic:"Torrance",      clinicSlug:"torrance",        lang:"English, Korean",  accepting:true,  focus:["Well-child","Developmental","Vaccinations"],           edu:"MD, UCLA" },
    { slug:"roberto-vargas",  name:"Dr. Roberto Vargas, MD",    specialty:"Childhood Obesity",    clinic:"Torrance",      clinicSlug:"torrance",        lang:"English, Spanish", accepting:true,  focus:["Obesity","Nutrition","Metabolic health"],              edu:"MD, UC Irvine" },
    { slug:"isabel-corona",   name:"Dr. Isabel Corona, MD",     specialty:"Pediatrics",           clinic:"Whittier",      clinicSlug:"whittier",        lang:"English, Spanish", accepting:true,  focus:["Primary care","Urgent care","Preventive care"],        edu:"MD, UCLA" },
    { slug:"andrew-chen",     name:"Dr. Andrew Chen, MD",       specialty:"ADHD & Behavioral",    clinic:"Whittier",      clinicSlug:"whittier",        lang:"English, Mandarin",accepting:true,  focus:["ADHD","Autism","Behavioral health"],                   edu:"MD, UC Davis" },
  ];
  // give each extra doctor the same minimal bio structure
  extra.forEach((d) => {
    if (!d.bio) d.bio = `Dr. ${d.name.split(" ")[1].replace(",","")} is a dedicated ${d.specialty} specialist serving the ${d.clinic} community, committed to compassionate, evidence-based pediatric care for every child.`;
  });
  KT.doctors = [...KT.doctors, ...extra];

  /* ── Service detail objects (20 services) ─────────────────────────────── */
  KT.serviceDetails = [
    { slug:"adhd-behavioral", name:"ADHD & Behavioral", icon:"sparkle", tagline:"Expert care for attention, behavior, and learning challenges.", description:"Our pediatric specialists provide comprehensive ADHD evaluations, behavioral support, and care coordination with schools — helping every child thrive in the classroom and at home.", conditions:["ADHD","Anxiety","Oppositional Defiant Disorder","Learning differences","Behavioral challenges"], careTypes:["primary-care","telehealth"], allClinics:true, relatedSlugs:["autism-special-needs","adolescent-medicine","well-child-exam"] },
    { slug:"adolescent-medicine", name:"Adolescent Medicine", icon:"users", tagline:"Specialized care for the unique health needs of teens.", description:"Adolescence comes with distinct challenges — physical changes, mental health, relationships, and identity. Our adolescent medicine specialists meet teens where they are, with confidential, non-judgmental care.", conditions:["Teen wellness","Reproductive health","Eating disorders","Depression & anxiety","Substance use screening"], careTypes:["primary-care","telehealth"], allClinics:false, relatedSlugs:["teenage-gynecology","sports-injuries","mental-health"] },
    { slug:"allergies", name:"Allergies", icon:"shield-plus", tagline:"Identify triggers, manage symptoms, and reclaim daily life.", description:"From food allergies and seasonal hay fever to pet dander and bee stings, our allergists develop personalized plans to reduce exposures and keep reactions manageable.", conditions:["Food allergies","Environmental allergies","Hay fever","Hives & eczema","Anaphylaxis prevention"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["asthma-allergy","sick-visit"] },
    { slug:"asthma-allergy", name:"Asthma & Allergy Center", icon:"heart-pulse", tagline:"LA's air is tough on lungs. We help kids breathe easier.", description:"Our dedicated Asthma & Allergy Center offers lung function testing, personalized action plans, allergy immunotherapy, and coordination with LA school nurse programs.", conditions:["Asthma","Allergic rhinitis","Eczema","Food allergy","Exercise-induced bronchospasm"], careTypes:["primary-care"], allClinics:false, relatedSlugs:["allergies","sick-visit","telehealth-service"] },
    { slug:"autism-special-needs", name:"Autism / Special Needs", icon:"heart", tagline:"Compassionate, specialist-coordinated care from diagnosis through adulthood.", description:"Early detection changes outcomes. We offer developmental screenings at every well-child visit, diagnostic coordination, and ongoing care for children with autism and other special needs — always with the whole family in mind.", conditions:["Autism Spectrum Disorder","Global developmental delay","Intellectual disability","Sensory processing","Communication differences"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["adhd-behavioral","well-child-exam","adolescent-medicine"] },
    { slug:"childhood-obesity", name:"Childhood Obesity", icon:"award", tagline:"Healthy weight, healthy life — without shame or fad diets.", description:"We take a whole-child approach to weight management: nutrition counseling, family-centered goal-setting, activity coaching, and where appropriate, medical support — all in a judgment-free environment.", conditions:["Obesity","Pre-diabetes","High cholesterol","Metabolic syndrome","Poor nutrition"], careTypes:["primary-care","telehealth"], allClinics:true, relatedSlugs:["nutrition","well-child-exam","adolescent-medicine"] },
    { slug:"covid-vaccine", name:"Covid-19 Vaccine", icon:"syringe", tagline:"Protecting kids and families with the latest Covid-19 vaccines.", description:"We carry the full updated Covid-19 vaccine schedule for all ages 6 months and up. Walk-ins welcome. Medi-Cal and L.A. Care covered — no cost at most clinics.", conditions:["Covid-19 prevention","Immunocompromised patients","Household protection"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["free-vaccines","well-child-exam","sick-visit"] },
    { slug:"expectant-parents", name:"Expectant Parents", icon:"baby", tagline:"Your pediatric partnership starts before baby arrives.", description:"Meet your future pediatrician before the birth. Our prenatal visits cover feeding choices, safe sleep, newborn care basics, and how to set up your medical home — so day one feels less overwhelming.", conditions:["Pre-birth pediatric visit","Feeding plan","Safe sleep counseling","Insurance verification","Nursery preparation"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["newborn-care","well-child-exam"] },
    { slug:"free-vaccines", name:"Free Vaccines", icon:"shield-plus", tagline:"No insurance required. Every child deserves protection.", description:"Through the Vaccines for Children (VFC) program and L.A. County partnerships, we offer the complete childhood immunization schedule at no cost to eligible families. Walk-ins welcome.", conditions:["All routine childhood vaccines","Flu vaccine","Covid-19 vaccine","Catch-up immunizations"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["covid-vaccine","well-child-exam","walk-ins"] },
    { slug:"newborn-care", name:"Newborn Care", icon:"baby", tagline:"Expert support from day one — for baby and for you.", description:"Our newborn care program covers all hospital discharge follow-ups, jaundice monitoring, weight checks, feeding support, and those 2 AM questions new parents have. We answer calls and messages same day.", conditions:["Newborn wellness","Jaundice","Feeding difficulties","Safe sleep","Colic & reflux"], careTypes:["primary-care","telehealth"], allClinics:true, relatedSlugs:["expectant-parents","well-child-exam","telehealth-service"] },
    { slug:"nutrition", name:"Nutrition", icon:"award", tagline:"Healthy eating habits that last a lifetime.", description:"Our registered dietitians and nutrition-trained pediatricians build practical, culturally sensitive eating plans for picky eaters, athletes, kids with metabolic conditions, and everyone in between.", conditions:["Picky eating","Failure to thrive","Eating disorders","Overweight","Sports nutrition"], careTypes:["primary-care","telehealth"], allClinics:true, relatedSlugs:["childhood-obesity","adolescent-medicine","well-child-exam"] },
    { slug:"infectious-disease", name:"Pediatric Infectious Disease", icon:"shield-plus", tagline:"Complex infections, rare conditions, antibiotic stewardship.", description:"For persistent fevers, unusual infections, post-Covid conditions, and immunocompromised children, our infectious disease specialists offer consultation and ongoing management — often in coordination with CHLA and Cedars-Sinai.", conditions:["Prolonged fever","HIV care","Recurrent infections","Travel medicine","Post-Covid MIS-C"], careTypes:["primary-care"], allClinics:false, relatedSlugs:["sick-visit","covid-vaccine","well-child-exam"] },
    { slug:"physicals", name:"Physicals", icon:"file", tagline:"School, sports, and camp physicals — same day at most locations.", description:"State-required physical forms, sports clearance, and camp physicals are available at all clinics, often same-day. Digital forms sent directly to your school or program.", conditions:["School physical","Sports clearance","Camp physical","Pre-op clearance","DOT/CDL (adolescent)"], careTypes:["primary-care","telehealth"], allClinics:true, relatedSlugs:["sports-injuries","well-child-exam","same-day-visit"] },
    { slug:"same-day-visit", name:"Same-Day Visit", icon:"clock", tagline:"Sick today? We'll see them today.", description:"We reserve slots at every clinic for same-day sick visits. Call before 9 AM or book online — we'll find you a slot that day so your child doesn't wait until tomorrow.", conditions:["Sick visit","Fever","Ear infection","Rash","Minor injuries"], careTypes:["primary-care","urgent-care","telehealth"], allClinics:true, relatedSlugs:["sick-visit","walk-ins","telehealth-service"] },
    { slug:"sick-visit", name:"Sick Visit", icon:"heart-pulse", tagline:"From sniffles to strep — we're open when your kids need us.", description:"Our sick visit clinics handle the full range of childhood illness: fevers, ear infections, strep throat, vomiting, rashes, and more. Evening and weekend hours at most locations.", conditions:["Fever","Ear infection","Strep throat","RSV","Stomach bug","Pink eye","Rash"], careTypes:["primary-care","urgent-care","telehealth"], allClinics:true, relatedSlugs:["urgent-care-svc","same-day-visit","telehealth-service"] },
    { slug:"sports-injuries", name:"Sports Injuries", icon:"award", tagline:"Back in the game, safely.", description:"Our sports medicine-trained pediatricians evaluate and treat sprains, fractures, concussions, overuse injuries, and growing pain syndromes — with return-to-play plans and school accommodation letters.", conditions:["Sprain & strain","Growth plate injury","Concussion","Stress fracture","Overuse syndrome"], careTypes:["primary-care","urgent-care"], allClinics:false, relatedSlugs:["physicals","urgent-care-svc","adolescent-medicine"] },
    { slug:"teenage-gynecology", name:"Teenage Gynecology", icon:"heart", tagline:"Private, compassionate reproductive health care for adolescent girls.", description:"Our adolescent gynecology services cover menstrual health, pelvic pain, contraceptive counseling, HPV vaccination, and STI screening — in a private, judgment-free setting with female providers available.", conditions:["Menstrual irregularities","PCOS","Pelvic pain","Contraceptive counseling","HPV vaccination"], careTypes:["primary-care"], allClinics:false, relatedSlugs:["adolescent-medicine","physicals"] },
    { slug:"telehealth-service", name:"Telehealth", icon:"video", tagline:"Your child's doctor, on screen — usually same day.", description:"Video visits for non-emergency concerns: colds, rashes, pink eye, minor infections, prescription refills, mental health follow-ups, and nutrition counseling. English and Spanish-speaking providers available every day.", conditions:["Minor illness","Prescription refill","Rash","Behavioral follow-up","Nutrition counseling"], careTypes:["telehealth"], allClinics:true, relatedSlugs:["same-day-visit","sick-visit","adhd-behavioral"] },
    { slug:"walk-ins", name:"Walk-Ins", icon:"map-pin", tagline:"No appointment needed at extended-hours clinics.", description:"Eight Kids & Teens locations welcome walk-in patients on evenings and weekends. No appointment needed — just bring your insurance card or let us verify coverage on arrival.", conditions:["Urgent sick visit","Injury","Fever","Ear infection","Minor lacerations"], careTypes:["urgent-care"], allClinics:false, relatedSlugs:["urgent-care-svc","same-day-visit","sick-visit"] },
    { slug:"well-child-exam", name:"Well Child Exam", icon:"check-circle", tagline:"The checkup that keeps your child on track, year after year.", description:"From newborn through age 21, our well-child exams track growth, development, vision, hearing, and social-emotional milestones — plus vaccines, blood work, and the chance to ask every question you've been saving up.", conditions:["Growth & development","Immunizations","Vision & hearing screening","Developmental milestones","School readiness"], careTypes:["primary-care"], allClinics:true, relatedSlugs:["newborn-care","physicals","adhd-behavioral"] },
  ];

  // Build a reverse lookup: service slug → clinics that offer it
  KT.serviceDetails.forEach((s) => {
    s.clinics = s.allClinics ? KT.locations : KT.locations.filter((l) => {
      if (s.slug === "urgent-care-svc" || s.slug === "walk-ins") return l.urgent;
      if (s.slug === "asthma-allergy" || s.slug === "infectious-disease" || s.slug === "sports-injuries" ||
          s.slug === "teenage-gynecology" || s.slug === "adolescent-medicine") return ["northridge","pasadena","glendale","hollywood","downey","whittier"].includes(l.slug);
      return true;
    });
  });

  // Index by slug for fast lookup
  KT.serviceBySlug = {};
  KT.serviceDetails.forEach((s) => { KT.serviceBySlug[s.slug] = s; });
  KT.doctorBySlug = {};
  KT.doctors.forEach((d) => { KT.doctorBySlug[d.slug] = d; });
})();
